// Export pages
export '/login/login_widget.dart' show LoginWidget;
export '/create_account1/create_account1_widget.dart' show CreateAccount1Widget;
export '/create_q_rcode2/create_q_rcode2_widget.dart' show CreateQRcode2Widget;
export '/hom_screen/hom_screen_widget.dart' show HomScreenWidget;
export '/q_rcode_screen1/q_rcode_screen1_widget.dart' show QRcodeScreen1Widget;
export '/create_q_rcode3/create_q_rcode3_widget.dart' show CreateQRcode3Widget;
export '/create_q_rcode4/create_q_rcode4_widget.dart' show CreateQRcode4Widget;
export '/q_rcode_screen2/q_rcode_screen2_widget.dart' show QRcodeScreen2Widget;
export '/q_rcode_screen3/q_rcode_screen3_widget.dart' show QRcodeScreen3Widget;
export '/login_component/login_component_widget.dart' show LoginComponentWidget;
export '/settings/settings_widget.dart' show SettingsWidget;
export '/test/test_widget.dart' show TestWidget;
export '/signup/signup_widget.dart' show SignupWidget;
export '/edit_profile/edit_profile_widget.dart' show EditProfileWidget;
export '/privacy_policy/privacy_policy_widget.dart' show PrivacyPolicyWidget;
export '/security_page/security_page_widget.dart' show SecurityPageWidget;
export '/qr_detail/qr_detail_widget.dart' show QrDetailWidget;
export '/edit_qr_code/edit_qr_code_widget.dart' show EditQrCodeWidget;
